
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* font
* filename: D:/Projekty/Nauka_STM/lcd-image-converter-20190317/test2.xml
* name: font_msSansSerif_14
* family: MS Sans Serif
* size: 14
* style: Normal
* included characters:  !"#$%&'()*+,-./0123456789:;<=>?\x0040ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~\x007f
* antialiasing: no
* type: proportional
* encoding: UTF-8
* unicode bom: yes
*
* preset name: Monochrome for sh1106
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: right_to_left
*  line scan direction: backward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
 typedef struct {
     long int code;
     const tImage *image;
     } tChar;
 typedef struct {
     int length;
     const tChar *chars;
     } tFont;
*/

#include <stdint.h>
#include "lcd_service.h"


#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x20[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x20 = { image_data_font_msSansSerif_14_0x20,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x21[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x0b, 
    0x00
};
static const tImage font_msSansSerif_14_0x21 = { image_data_font_msSansSerif_14_0x21,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x22[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙█∙∙█∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00, 
    0x3c, 
    0x00, 
    0x00, 
    0x3c, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x22 = { image_data_font_msSansSerif_14_0x22,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x23[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙█∙∙█∙
    // ∙∙∙█∙∙█∙
    // ∙∙∙█∙∙█∙
    // ∙███████
    // ∙∙█∙∙█∙∙
    // ∙∙█∙∙█∙∙
    // ███████∙
    // ∙█∙∙█∙∙∙
    // ∙█∙∙█∙∙∙
    // ∙█∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0x20, 
    0xe0, 
    0x3c, 
    0x20, 
    0xe0, 
    0x3c, 
    0x20, 
    0x01, 
    0x0f, 
    0x01, 
    0x01, 
    0x0f, 
    0x01, 
    0x01, 
    0x00
};
static const tImage font_msSansSerif_14_0x23 = { image_data_font_msSansSerif_14_0x23,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x24[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙███∙∙
    // ∙█∙█∙█∙
    // ∙█∙█∙█∙
    // ∙█∙█∙∙∙
    // ∙∙███∙∙
    // ∙∙∙█∙█∙
    // ∙∙∙█∙█∙
    // ∙█∙█∙█∙
    // ∙∙███∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x70, 
    0x88, 
    0xfc, 
    0x88, 
    0x30, 
    0x00, 
    0x00, 
    0x04, 
    0x08, 
    0x1f, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x24 = { image_data_font_msSansSerif_14_0x24,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x25[24] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙██∙∙∙∙∙∙∙∙
    // ∙█∙∙█∙∙∙∙█∙∙
    // ∙█∙∙█∙∙∙█∙∙∙
    // ∙∙██∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙█∙∙∙∙∙
    // ∙∙∙∙∙█∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙██∙∙
    // ∙∙∙█∙∙∙█∙∙█∙
    // ∙∙█∙∙∙∙█∙∙█∙
    // ∙∙∙∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0x18, 
    0x24, 
    0x24, 
    0x18, 
    0x80, 
    0x40, 
    0x20, 
    0x10, 
    0x08, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x04, 
    0x02, 
    0x01, 
    0x00, 
    0x00, 
    0x06, 
    0x09, 
    0x09, 
    0x06, 
    0x00
};
static const tImage font_msSansSerif_14_0x25 = { image_data_font_msSansSerif_14_0x25,
    12, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x26[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙∙
    // ∙∙█∙∙█∙∙∙
    // ∙∙█∙∙█∙∙∙
    // ∙∙█∙∙█∙∙∙
    // ∙∙∙██∙∙∙∙
    // ∙∙█∙█∙∙∙∙
    // ∙█∙∙∙█∙∙∙
    // ∙█∙∙∙█∙█∙
    // ∙█∙∙∙∙█∙∙
    // ∙∙████∙█∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0x00, 
    0xb8, 
    0x44, 
    0xc4, 
    0x38, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x0b, 
    0x04, 
    0x0a, 
    0x00
};
static const tImage font_msSansSerif_14_0x26 = { image_data_font_msSansSerif_14_0x26,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x27[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x3c, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x27 = { image_data_font_msSansSerif_14_0x27,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x28[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙█
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙∙█
    0x00, 
    0xe0, 
    0x18, 
    0x04, 
    0x00, 
    0x0f, 
    0x30, 
    0x40
};
static const tImage font_msSansSerif_14_0x28 = { image_data_font_msSansSerif_14_0x28,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x29[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // █∙∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙█∙∙
    // ∙█∙∙
    // █∙∙∙
    0x04, 
    0x18, 
    0xe0, 
    0x00, 
    0x40, 
    0x30, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x29 = { image_data_font_msSansSerif_14_0x29,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2a[10] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙█∙∙
    // █∙█∙█
    // ∙███∙
    // ██∙██
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    0x28, 
    0x30, 
    0x1c, 
    0x30, 
    0x28, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x2a = { image_data_font_msSansSerif_14_0x2a,
    5, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2b[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙█████∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x80, 
    0x80, 
    0xe0, 
    0x80, 
    0x80, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x03, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x2b = { image_data_font_msSansSerif_14_0x2b,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2c[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // █∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0x10, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x2c = { image_data_font_msSansSerif_14_0x2c,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2d[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ████
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x80, 
    0x80, 
    0x80, 
    0x80, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x2d = { image_data_font_msSansSerif_14_0x2d,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2e[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x2e = { image_data_font_msSansSerif_14_0x2e,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x2f[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙∙∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0xe0, 
    0x1c, 
    0x00, 
    0x00, 
    0x38, 
    0x07, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x2f = { image_data_font_msSansSerif_14_0x2f,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x30[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xf8, 
    0x04, 
    0x04, 
    0x04, 
    0xf8, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x30 = { image_data_font_msSansSerif_14_0x30,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x31[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙███∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x08, 
    0x08, 
    0xfc, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x31 = { image_data_font_msSansSerif_14_0x31,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x32[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x18, 
    0x04, 
    0x84, 
    0x44, 
    0x38, 
    0x00, 
    0x00, 
    0x0e, 
    0x09, 
    0x08, 
    0x08, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x32 = { image_data_font_msSansSerif_14_0x32,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x33[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙██∙∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x08, 
    0x04, 
    0x44, 
    0x44, 
    0xb8, 
    0x00, 
    0x00, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x33 = { image_data_font_msSansSerif_14_0x33,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x34[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙██∙
    // ∙∙∙█∙█∙
    // ∙∙∙█∙█∙
    // ∙∙█∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█████∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x80, 
    0x40, 
    0x30, 
    0x08, 
    0xfc, 
    0x00, 
    0x00, 
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x34 = { image_data_font_msSansSerif_14_0x34,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x35[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙████∙∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x44, 
    0x44, 
    0x44, 
    0x84, 
    0x00, 
    0x00, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x35 = { image_data_font_msSansSerif_14_0x35,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x36[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙██∙∙
    // ∙██∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xf8, 
    0x84, 
    0x44, 
    0x44, 
    0x88, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x36 = { image_data_font_msSansSerif_14_0x36,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x37[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x04, 
    0x04, 
    0x84, 
    0x64, 
    0x1c, 
    0x00, 
    0x00, 
    0x00, 
    0x0e, 
    0x01, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x37 = { image_data_font_msSansSerif_14_0x37,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x38[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xb8, 
    0x44, 
    0x44, 
    0x44, 
    0xb8, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x38 = { image_data_font_msSansSerif_14_0x38,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x39[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x78, 
    0x84, 
    0x84, 
    0x44, 
    0xf8, 
    0x00, 
    0x00, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x39 = { image_data_font_msSansSerif_14_0x39,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3a[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x20, 
    0x00, 
    0x00, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x3a = { image_data_font_msSansSerif_14_0x3a,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3b[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // █∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0x20, 
    0x00, 
    0x10, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x3b = { image_data_font_msSansSerif_14_0x3b,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3c[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙██∙
    // ∙∙∙██∙∙
    // ∙∙██∙∙∙
    // ∙██∙∙∙∙
    // ∙∙██∙∙∙
    // ∙∙∙██∙∙
    // ∙∙∙∙██∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x80, 
    0xc0, 
    0x60, 
    0x30, 
    0x10, 
    0x00, 
    0x00, 
    0x00, 
    0x01, 
    0x03, 
    0x06, 
    0x04, 
    0x00
};
static const tImage font_msSansSerif_14_0x3c = { image_data_font_msSansSerif_14_0x3c,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3d[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙█████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x00, 
    0x00, 
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x00
};
static const tImage font_msSansSerif_14_0x3d = { image_data_font_msSansSerif_14_0x3d,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3e[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙██∙∙∙∙
    // ∙∙██∙∙∙
    // ∙∙∙██∙∙
    // ∙∙∙∙██∙
    // ∙∙∙██∙∙
    // ∙∙██∙∙∙
    // ∙██∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x10, 
    0x30, 
    0x60, 
    0xc0, 
    0x80, 
    0x00, 
    0x00, 
    0x04, 
    0x06, 
    0x03, 
    0x01, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x3e = { image_data_font_msSansSerif_14_0x3e,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x3f[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x18, 
    0x04, 
    0x84, 
    0x44, 
    0x38, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0b, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x3f = { image_data_font_msSansSerif_14_0x3f,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x40[28] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙████∙∙∙∙∙
    // ∙∙∙██∙∙∙∙██∙∙∙
    // ∙∙█∙∙∙∙∙∙∙∙█∙∙
    // ∙∙█∙∙∙∙∙∙∙∙█∙∙
    // ∙█∙∙∙∙████∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙∙█∙
    // ∙█∙∙∙█∙∙█∙∙∙█∙
    // ∙∙█∙∙∙██∙███∙∙
    // ∙∙█∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙██∙∙∙∙∙██∙∙
    // ∙∙∙∙∙█████∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xe0, 
    0x18, 
    0x04, 
    0x04, 
    0xc2, 
    0x22, 
    0x22, 
    0x22, 
    0xe4, 
    0x04, 
    0x18, 
    0xe0, 
    0x00, 
    0x00, 
    0x01, 
    0x06, 
    0x08, 
    0x08, 
    0x11, 
    0x12, 
    0x12, 
    0x11, 
    0x12, 
    0x0a, 
    0x0a, 
    0x01, 
    0x00
};
static const tImage font_msSansSerif_14_0x40 = { image_data_font_msSansSerif_14_0x40,
    14, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x41[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙███████∙
    // ∙█∙∙∙∙∙█∙
    // █∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0x00, 
    0xc0, 
    0x30, 
    0x0c, 
    0x30, 
    0xc0, 
    0x00, 
    0x00, 
    0x0c, 
    0x03, 
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x01, 
    0x03, 
    0x0c
};
static const tImage font_msSansSerif_14_0x41 = { image_data_font_msSansSerif_14_0x41,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x42[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙██████∙∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙██████∙∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙██████∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0xb8, 
    0x00, 
    0x00, 
    0x0f, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x42 = { image_data_font_msSansSerif_14_0x42,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x43[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙
    // ∙∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙█
    // ∙∙█∙∙∙∙█∙
    // ∙∙∙████∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0xf0, 
    0x08, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x08, 
    0x10, 
    0x00, 
    0x03, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x02
};
static const tImage font_msSansSerif_14_0x43 = { image_data_font_msSansSerif_14_0x43,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x44[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙██████∙∙∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙██████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x08, 
    0xf0, 
    0x00, 
    0x00, 
    0x0f, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x03, 
    0x00
};
static const tImage font_msSansSerif_14_0x44 = { image_data_font_msSansSerif_14_0x44,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x45[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙███████∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙██████∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙███████∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0x04, 
    0x00, 
    0x00, 
    0x0f, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x45 = { image_data_font_msSansSerif_14_0x45,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x46[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙███████
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0x44, 
    0x04, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x46 = { image_data_font_msSansSerif_14_0x46,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x47[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙███∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙∙█∙∙∙∙██∙
    // ∙∙∙████∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xf0, 
    0x08, 
    0x04, 
    0x04, 
    0x04, 
    0x84, 
    0x88, 
    0x90, 
    0x00, 
    0x00, 
    0x03, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x47 = { image_data_font_msSansSerif_14_0x47,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x48[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙████████∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0x40, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x48 = { image_data_font_msSansSerif_14_0x48,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x49[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x49 = { image_data_font_msSansSerif_14_0x49,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4a[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x06, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x4a = { image_data_font_msSansSerif_14_0x4a,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4b[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙█∙∙∙
    // ∙█∙█∙∙∙∙
    // ∙██∙∙∙∙∙
    // ∙█∙█∙∙∙∙
    // ∙█∙∙█∙∙∙
    // ∙█∙∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x40, 
    0xa0, 
    0x10, 
    0x08, 
    0x04, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x01, 
    0x02, 
    0x04, 
    0x08
};
static const tImage font_msSansSerif_14_0x4b = { image_data_font_msSansSerif_14_0x4b,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4c[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙██████
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08
};
static const tImage font_msSansSerif_14_0x4c = { image_data_font_msSansSerif_14_0x4c,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4d[22] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙█∙
    // ∙██∙∙∙∙∙██∙
    // ∙██∙∙∙∙∙██∙
    // ∙█∙█∙∙∙█∙█∙
    // ∙█∙█∙∙∙█∙█∙
    // ∙█∙∙█∙█∙∙█∙
    // ∙█∙∙█∙█∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x30, 
    0xc0, 
    0x00, 
    0x00, 
    0x00, 
    0xc0, 
    0x30, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x4d = { image_data_font_msSansSerif_14_0x4d,
    11, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4e[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙██∙∙∙∙∙█∙
    // ∙█∙█∙∙∙∙█∙
    // ∙█∙█∙∙∙∙█∙
    // ∙█∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙█∙
    // ∙█∙∙∙∙█∙█∙
    // ∙█∙∙∙∙█∙█∙
    // ∙█∙∙∙∙∙██∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x08, 
    0x30, 
    0x40, 
    0x80, 
    0x00, 
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x03, 
    0x04, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x4e = { image_data_font_msSansSerif_14_0x4e,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x4f[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙∙∙████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xf0, 
    0x08, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x08, 
    0xf0, 
    0x00, 
    0x00, 
    0x03, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x03, 
    0x00
};
static const tImage font_msSansSerif_14_0x4f = { image_data_font_msSansSerif_14_0x4f,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x50[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙██████∙∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙█∙
    // ∙██████∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0x84, 
    0x84, 
    0x48, 
    0x30, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x50 = { image_data_font_msSansSerif_14_0x50,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x51[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙████∙∙∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙█∙█∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙∙∙████∙█∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xf0, 
    0x08, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x08, 
    0xf0, 
    0x00, 
    0x00, 
    0x03, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x0a, 
    0x04, 
    0x0b, 
    0x00
};
static const tImage font_msSansSerif_14_0x51 = { image_data_font_msSansSerif_14_0x51,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x52[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙██████∙∙∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙∙
    // ∙███████∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x84, 
    0x84, 
    0x84, 
    0x84, 
    0x84, 
    0xc8, 
    0x30, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x07, 
    0x08
};
static const tImage font_msSansSerif_14_0x52 = { image_data_font_msSansSerif_14_0x52,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x53[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙█████∙∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙
    // ∙∙███∙∙∙∙
    // ∙∙∙∙∙██∙∙
    // ∙∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙∙█████∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0x38, 
    0x44, 
    0x44, 
    0x44, 
    0x84, 
    0x84, 
    0x18, 
    0x00, 
    0x00, 
    0x06, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x53 = { image_data_font_msSansSerif_14_0x53,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x54[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █████████
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0xfc, 
    0x04, 
    0x04, 
    0x04, 
    0x04, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x54 = { image_data_font_msSansSerif_14_0x54,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x55[20] = {
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙█∙
    // ∙∙█∙∙∙∙█∙∙
    // ∙∙∙████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x03, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x03, 
    0x00
};
static const tImage font_msSansSerif_14_0x55 = { image_data_font_msSansSerif_14_0x55,
    10, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x56[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙█∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0c, 
    0x30, 
    0xc0, 
    0x00, 
    0x00, 
    0x00, 
    0xc0, 
    0x30, 
    0x0c, 
    0x00, 
    0x00, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x56 = { image_data_font_msSansSerif_14_0x56,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x57[26] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙█∙∙∙∙∙█
    // █∙∙∙∙∙█∙∙∙∙∙█
    // █∙∙∙∙∙█∙∙∙∙∙█
    // ∙█∙∙∙█∙█∙∙∙█∙
    // ∙█∙∙∙█∙█∙∙∙█∙
    // ∙∙█∙█∙∙∙█∙█∙∙
    // ∙∙█∙█∙∙∙█∙█∙∙
    // ∙∙█∙█∙∙∙█∙█∙∙
    // ∙∙∙█∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x1c, 
    0x60, 
    0x80, 
    0x00, 
    0x80, 
    0x60, 
    0x1c, 
    0x60, 
    0x80, 
    0x00, 
    0x80, 
    0x60, 
    0x1c, 
    0x00, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00, 
    0x00, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x57 = { image_data_font_msSansSerif_14_0x57,
    13, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x58[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙█
    // █∙∙∙∙∙∙█
    // ∙█∙∙∙∙█∙
    // ∙∙█∙∙█∙∙
    // ∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙
    // ∙∙█∙∙█∙∙
    // ∙█∙∙∙∙█∙
    // █∙∙∙∙∙∙█
    // █∙∙∙∙∙∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x0c, 
    0x10, 
    0x20, 
    0xc0, 
    0xc0, 
    0x20, 
    0x10, 
    0x0c, 
    0x0c, 
    0x02, 
    0x01, 
    0x00, 
    0x00, 
    0x01, 
    0x02, 
    0x0c
};
static const tImage font_msSansSerif_14_0x58 = { image_data_font_msSansSerif_14_0x58,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x59[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙█∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙∙█∙█∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙█∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x0c, 
    0x10, 
    0x20, 
    0x40, 
    0x80, 
    0x40, 
    0x20, 
    0x10, 
    0x0c, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x59 = { image_data_font_msSansSerif_14_0x59,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5a[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙∙█∙∙
    // ∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙██████∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0x04, 
    0x04, 
    0x84, 
    0x44, 
    0x34, 
    0x0c, 
    0x00, 
    0x00, 
    0x0c, 
    0x0b, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x5a = { image_data_font_msSansSerif_14_0x5a,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5b[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙███
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙███
    0x00, 
    0xfc, 
    0x04, 
    0x04, 
    0x00, 
    0x7f, 
    0x40, 
    0x40
};
static const tImage font_msSansSerif_14_0x5b = { image_data_font_msSansSerif_14_0x5b,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5c[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙█∙∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙█∙∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙█∙
    // ∙∙∙∙∙∙
    0x00, 
    0x1c, 
    0xe0, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x07, 
    0x38, 
    0x00
};
static const tImage font_msSansSerif_14_0x5c = { image_data_font_msSansSerif_14_0x5c,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5d[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ███∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ∙∙█∙
    // ███∙
    0x04, 
    0x04, 
    0xfc, 
    0x00, 
    0x40, 
    0x40, 
    0x7f, 
    0x00
};
static const tImage font_msSansSerif_14_0x5d = { image_data_font_msSansSerif_14_0x5d,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5e[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙█∙∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0x08, 
    0x04, 
    0x02, 
    0x04, 
    0x08, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x5e = { image_data_font_msSansSerif_14_0x5e,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x5f[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ███████
    // ∙∙∙∙∙∙∙
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0x20
};
static const tImage font_msSansSerif_14_0x5f = { image_data_font_msSansSerif_14_0x5f,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x60[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙∙
    // ∙∙█∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 
    0x04, 
    0x08, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x60 = { image_data_font_msSansSerif_14_0x60,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x61[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙█████∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙█
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0x40, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xa0, 
    0xc0, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x08
};
static const tImage font_msSansSerif_14_0x61 = { image_data_font_msSansSerif_14_0x61,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x62[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙█∙███∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x40, 
    0x20, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x0f, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x62 = { image_data_font_msSansSerif_14_0x62,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x63[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙████∙
    // ∙█∙∙∙∙█
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙█
    // ∙∙████∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0x40, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x04
};
static const tImage font_msSansSerif_14_0x63 = { image_data_font_msSansSerif_14_0x63,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x64[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x40, 
    0xfc, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x64 = { image_data_font_msSansSerif_14_0x64,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x65[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██████∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x07, 
    0x09, 
    0x09, 
    0x09, 
    0x09, 
    0x05, 
    0x00
};
static const tImage font_msSansSerif_14_0x65 = { image_data_font_msSansSerif_14_0x65,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x66[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙█
    // ∙█∙
    // ∙█∙
    // ███
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x20, 
    0xf8, 
    0x24, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x66 = { image_data_font_msSansSerif_14_0x66,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x67[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙████∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x40, 
    0xe0, 
    0x00, 
    0x00, 
    0x07, 
    0x48, 
    0x48, 
    0x48, 
    0x44, 
    0x3f, 
    0x00
};
static const tImage font_msSansSerif_14_0x67 = { image_data_font_msSansSerif_14_0x67,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x68[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙██∙∙
    // ∙██∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x40, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x68 = { image_data_font_msSansSerif_14_0x68,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x69[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0xe4, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x69 = { image_data_font_msSansSerif_14_0x69,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6a[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // █∙∙
    0x00, 
    0xe4, 
    0x00, 
    0x40, 
    0x3f, 
    0x00
};
static const tImage font_msSansSerif_14_0x6a = { image_data_font_msSansSerif_14_0x6a,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6b[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙█∙∙
    // ∙█∙█∙∙∙
    // ∙███∙∙∙
    // ∙█∙∙█∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙∙█
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x80, 
    0x40, 
    0x20, 
    0x00, 
    0x00, 
    0x0f, 
    0x01, 
    0x01, 
    0x02, 
    0x04, 
    0x08
};
static const tImage font_msSansSerif_14_0x6b = { image_data_font_msSansSerif_14_0x6b,
    7, 16, 8};
#endif

#if (0x049 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6c[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x6c = { image_data_font_msSansSerif_14_0x6c,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6d[22] = {
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙█∙██∙∙██∙∙
    // ∙██∙∙██∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙█∙∙∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙
    0x00, 
    0xe0, 
    0x40, 
    0x20, 
    0x20, 
    0xc0, 
    0x40, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x6d = { image_data_font_msSansSerif_14_0x6d,
    11, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6e[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙██∙∙
    // ∙██∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xe0, 
    0x40, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x0f, 
    0x00, 
    0x00, 
    0x00, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x6e = { image_data_font_msSansSerif_14_0x6e,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x6f[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙████∙∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙∙████∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x6f = { image_data_font_msSansSerif_14_0x6f,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x70[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙█∙███∙∙
    // ∙██∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙██∙∙∙█∙
    // ∙█∙███∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    // ∙█∙∙∙∙∙∙
    0x00, 
    0xe0, 
    0x40, 
    0x20, 
    0x20, 
    0x20, 
    0xc0, 
    0x00, 
    0x00, 
    0x7f, 
    0x04, 
    0x08, 
    0x08, 
    0x08, 
    0x07, 
    0x00
};
static const tImage font_msSansSerif_14_0x70 = { image_data_font_msSansSerif_14_0x70,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x71[16] = {
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙
    // ∙∙███∙█∙
    // ∙█∙∙∙██∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙∙█∙
    // ∙█∙∙∙██∙
    // ∙∙███∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    // ∙∙∙∙∙∙█∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x40, 
    0xe0, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x08, 
    0x04, 
    0x7f, 
    0x00
};
static const tImage font_msSansSerif_14_0x71 = { image_data_font_msSansSerif_14_0x71,
    8, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x72[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙█∙█
    // ∙██∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙█∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 
    0xe0, 
    0x40, 
    0x20, 
    0x00, 
    0x0f, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x72 = { image_data_font_msSansSerif_14_0x72,
    4, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x73[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙███∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙∙∙
    // ∙∙███∙∙
    // ∙∙∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙███∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xc0, 
    0x20, 
    0x20, 
    0x20, 
    0x40, 
    0x00, 
    0x00, 
    0x04, 
    0x09, 
    0x09, 
    0x09, 
    0x06, 
    0x00
};
static const tImage font_msSansSerif_14_0x73 = { image_data_font_msSansSerif_14_0x73,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x74[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ███
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙∙█
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    0x20, 
    0xf8, 
    0x20, 
    0x00, 
    0x07, 
    0x08
};
static const tImage font_msSansSerif_14_0x74 = { image_data_font_msSansSerif_14_0x74,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x75[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙█∙∙██∙
    // ∙∙██∙█∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x00, 
    0xe0, 
    0x00, 
    0x00, 
    0x00, 
    0xe0, 
    0x00, 
    0x00, 
    0x07, 
    0x08, 
    0x08, 
    0x04, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x75 = { image_data_font_msSansSerif_14_0x75,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x76[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // █∙∙∙∙∙█
    // █∙∙∙∙∙█
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙█∙█∙∙
    // ∙∙█∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    0x60, 
    0x80, 
    0x00, 
    0x00, 
    0x00, 
    0x80, 
    0x60, 
    0x00, 
    0x01, 
    0x06, 
    0x08, 
    0x06, 
    0x01, 
    0x00
};
static const tImage font_msSansSerif_14_0x76 = { image_data_font_msSansSerif_14_0x76,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x77[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // █∙∙∙█∙∙∙█
    // █∙∙∙█∙∙∙█
    // ∙█∙█∙█∙█∙
    // ∙█∙█∙█∙█∙
    // ∙█∙█∙█∙█∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙█∙∙∙█∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x60, 
    0x80, 
    0x00, 
    0x80, 
    0x60, 
    0x80, 
    0x00, 
    0x80, 
    0x60, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00, 
    0x03, 
    0x0c, 
    0x03, 
    0x00
};
static const tImage font_msSansSerif_14_0x77 = { image_data_font_msSansSerif_14_0x77,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x78[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // █∙∙∙∙█
    // ∙█∙∙█∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙∙██∙∙
    // ∙█∙∙█∙
    // █∙∙∙∙█
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x20, 
    0x40, 
    0x80, 
    0x80, 
    0x40, 
    0x20, 
    0x08, 
    0x04, 
    0x03, 
    0x03, 
    0x04, 
    0x08
};
static const tImage font_msSansSerif_14_0x78 = { image_data_font_msSansSerif_14_0x78,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x79[14] = {
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙
    // █∙∙∙∙∙█
    // █∙∙∙∙∙█
    // ∙█∙∙∙█∙
    // ∙█∙∙∙█∙
    // ∙∙█∙█∙∙
    // ∙∙█∙█∙∙
    // ∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙
    // ∙∙█∙∙∙∙
    // ██∙∙∙∙∙
    0x60, 
    0x80, 
    0x00, 
    0x00, 
    0x00, 
    0x80, 
    0x60, 
    0x40, 
    0x41, 
    0x26, 
    0x18, 
    0x06, 
    0x01, 
    0x00
};
static const tImage font_msSansSerif_14_0x79 = { image_data_font_msSansSerif_14_0x79,
    7, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7a[12] = {
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙████∙
    // ∙∙∙∙█∙
    // ∙∙∙█∙∙
    // ∙∙█∙∙∙
    // ∙∙█∙∙∙
    // ∙█∙∙∙∙
    // ∙████∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    // ∙∙∙∙∙∙
    0x00, 
    0x20, 
    0x20, 
    0xa0, 
    0x60, 
    0x00, 
    0x00, 
    0x0c, 
    0x0b, 
    0x08, 
    0x08, 
    0x00
};
static const tImage font_msSansSerif_14_0x7a = { image_data_font_msSansSerif_14_0x7a,
    6, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7b[10] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙██
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ██∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙██
    0x00, 
    0x00, 
    0xf8, 
    0x04, 
    0x04, 
    0x01, 
    0x01, 
    0x3e, 
    0x40, 
    0x40
};
static const tImage font_msSansSerif_14_0x7b = { image_data_font_msSansSerif_14_0x7b,
    5, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7c[6] = {
    // ∙∙∙
    // ∙∙∙
    // ∙∙∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    // ∙█∙
    0x00, 
    0xfc, 
    0x00, 
    0x00, 
    0x7f, 
    0x00
};
static const tImage font_msSansSerif_14_0x7c = { image_data_font_msSansSerif_14_0x7c,
    3, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7d[10] = {
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ∙∙∙∙∙
    // ██∙∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙∙██
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ∙∙█∙∙
    // ██∙∙∙
    0x04, 
    0x04, 
    0xf8, 
    0x00, 
    0x00, 
    0x40, 
    0x40, 
    0x3e, 
    0x01, 
    0x01
};
static const tImage font_msSansSerif_14_0x7d = { image_data_font_msSansSerif_14_0x7d,
    5, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7e[18] = {
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙██∙∙∙█∙
    // ∙█∙∙█∙∙█∙
    // ∙█∙∙∙██∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙∙∙∙∙
    0x00, 
    0x18, 
    0x04, 
    0x04, 
    0x08, 
    0x10, 
    0x10, 
    0x0c, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00, 
    0x00
};
static const tImage font_msSansSerif_14_0x7e = { image_data_font_msSansSerif_14_0x7e,
    9, 16, 8};
#endif

#if (0x0 == 0x0)
static const uint8_t image_data_font_msSansSerif_14_0x7f[8] = {
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙██∙
    // ∙∙∙∙
    // ∙∙∙∙
    // ∙∙∙∙
    0x00, 
    0xfc, 
    0xfc, 
    0x00, 
    0x00, 
    0x0f, 
    0x0f, 
    0x00
};
static const tImage font_msSansSerif_14_0x7f = { image_data_font_msSansSerif_14_0x7f,
    4, 16, 8};
#endif


static const tChar font_msSansSerif_14_array[] = {

#if (0x0 == 0x0)
  // character: ' '
  {0x20, &font_msSansSerif_14_0x20},
#else
  // character: ' ' == ''
  {0x20, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '!'
  {0x21, &font_msSansSerif_14_0x21},
#else
  // character: '!' == ''
  {0x21, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '"'
  {0x22, &font_msSansSerif_14_0x22},
#else
  // character: '"' == ''
  {0x22, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '#'
  {0x23, &font_msSansSerif_14_0x23},
#else
  // character: '#' == ''
  {0x23, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '$'
  {0x24, &font_msSansSerif_14_0x24},
#else
  // character: '$' == ''
  {0x24, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '%'
  {0x25, &font_msSansSerif_14_0x25},
#else
  // character: '%' == ''
  {0x25, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '&'
  {0x26, &font_msSansSerif_14_0x26},
#else
  // character: '&' == ''
  {0x26, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '''
  {0x27, &font_msSansSerif_14_0x27},
#else
  // character: ''' == ''
  {0x27, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '('
  {0x28, &font_msSansSerif_14_0x28},
#else
  // character: '(' == ''
  {0x28, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: ')'
  {0x29, &font_msSansSerif_14_0x29},
#else
  // character: ')' == ''
  {0x29, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '*'
  {0x2a, &font_msSansSerif_14_0x2a},
#else
  // character: '*' == ''
  {0x2a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '+'
  {0x2b, &font_msSansSerif_14_0x2b},
#else
  // character: '+' == ''
  {0x2b, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: ','
  {0x2c, &font_msSansSerif_14_0x2c},
#else
  // character: ',' == ''
  {0x2c, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '-'
  {0x2d, &font_msSansSerif_14_0x2d},
#else
  // character: '-' == ''
  {0x2d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '.'
  {0x2e, &font_msSansSerif_14_0x2e},
#else
  // character: '.' == ''
  {0x2e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '/'
  {0x2f, &font_msSansSerif_14_0x2f},
#else
  // character: '/' == ''
  {0x2f, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '0'
  {0x30, &font_msSansSerif_14_0x30},
#else
  // character: '0' == ''
  {0x30, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '1'
  {0x31, &font_msSansSerif_14_0x31},
#else
  // character: '1' == ''
  {0x31, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '2'
  {0x32, &font_msSansSerif_14_0x32},
#else
  // character: '2' == ''
  {0x32, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '3'
  {0x33, &font_msSansSerif_14_0x33},
#else
  // character: '3' == ''
  {0x33, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '4'
  {0x34, &font_msSansSerif_14_0x34},
#else
  // character: '4' == ''
  {0x34, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '5'
  {0x35, &font_msSansSerif_14_0x35},
#else
  // character: '5' == ''
  {0x35, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '6'
  {0x36, &font_msSansSerif_14_0x36},
#else
  // character: '6' == ''
  {0x36, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '7'
  {0x37, &font_msSansSerif_14_0x37},
#else
  // character: '7' == ''
  {0x37, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '8'
  {0x38, &font_msSansSerif_14_0x38},
#else
  // character: '8' == ''
  {0x38, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '9'
  {0x39, &font_msSansSerif_14_0x39},
#else
  // character: '9' == ''
  {0x39, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: ':'
  {0x3a, &font_msSansSerif_14_0x3a},
#else
  // character: ':' == ''
  {0x3a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: ';'
  {0x3b, &font_msSansSerif_14_0x3b},
#else
  // character: ';' == ''
  {0x3b, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '<'
  {0x3c, &font_msSansSerif_14_0x3c},
#else
  // character: '<' == ''
  {0x3c, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '='
  {0x3d, &font_msSansSerif_14_0x3d},
#else
  // character: '=' == ''
  {0x3d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '>'
  {0x3e, &font_msSansSerif_14_0x3e},
#else
  // character: '>' == ''
  {0x3e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '?'
  {0x3f, &font_msSansSerif_14_0x3f},
#else
  // character: '?' == ''
  {0x3f, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x0040'
  {0x40, &font_msSansSerif_14_0x40},
#else
  // character: '\x0040' == ''
  {0x40, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'A'
  {0x41, &font_msSansSerif_14_0x41},
#else
  // character: 'A' == ''
  {0x41, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'B'
  {0x42, &font_msSansSerif_14_0x42},
#else
  // character: 'B' == ''
  {0x42, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'C'
  {0x43, &font_msSansSerif_14_0x43},
#else
  // character: 'C' == ''
  {0x43, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'D'
  {0x44, &font_msSansSerif_14_0x44},
#else
  // character: 'D' == ''
  {0x44, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'E'
  {0x45, &font_msSansSerif_14_0x45},
#else
  // character: 'E' == ''
  {0x45, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'F'
  {0x46, &font_msSansSerif_14_0x46},
#else
  // character: 'F' == ''
  {0x46, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'G'
  {0x47, &font_msSansSerif_14_0x47},
#else
  // character: 'G' == ''
  {0x47, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'H'
  {0x48, &font_msSansSerif_14_0x48},
#else
  // character: 'H' == ''
  {0x48, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'I'
  {0x49, &font_msSansSerif_14_0x49},
#else
  // character: 'I' == ''
  {0x49, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'J'
  {0x4a, &font_msSansSerif_14_0x4a},
#else
  // character: 'J' == ''
  {0x4a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'K'
  {0x4b, &font_msSansSerif_14_0x4b},
#else
  // character: 'K' == ''
  {0x4b, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'L'
  {0x4c, &font_msSansSerif_14_0x4c},
#else
  // character: 'L' == ''
  {0x4c, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'M'
  {0x4d, &font_msSansSerif_14_0x4d},
#else
  // character: 'M' == ''
  {0x4d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'N'
  {0x4e, &font_msSansSerif_14_0x4e},
#else
  // character: 'N' == ''
  {0x4e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'O'
  {0x4f, &font_msSansSerif_14_0x4f},
#else
  // character: 'O' == ''
  {0x4f, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'P'
  {0x50, &font_msSansSerif_14_0x50},
#else
  // character: 'P' == ''
  {0x50, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Q'
  {0x51, &font_msSansSerif_14_0x51},
#else
  // character: 'Q' == ''
  {0x51, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'R'
  {0x52, &font_msSansSerif_14_0x52},
#else
  // character: 'R' == ''
  {0x52, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'S'
  {0x53, &font_msSansSerif_14_0x53},
#else
  // character: 'S' == ''
  {0x53, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'T'
  {0x54, &font_msSansSerif_14_0x54},
#else
  // character: 'T' == ''
  {0x54, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'U'
  {0x55, &font_msSansSerif_14_0x55},
#else
  // character: 'U' == ''
  {0x55, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'V'
  {0x56, &font_msSansSerif_14_0x56},
#else
  // character: 'V' == ''
  {0x56, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'W'
  {0x57, &font_msSansSerif_14_0x57},
#else
  // character: 'W' == ''
  {0x57, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'X'
  {0x58, &font_msSansSerif_14_0x58},
#else
  // character: 'X' == ''
  {0x58, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Y'
  {0x59, &font_msSansSerif_14_0x59},
#else
  // character: 'Y' == ''
  {0x59, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'Z'
  {0x5a, &font_msSansSerif_14_0x5a},
#else
  // character: 'Z' == ''
  {0x5a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '['
  {0x5b, &font_msSansSerif_14_0x5b},
#else
  // character: '[' == ''
  {0x5b, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '\'
  {0x5c, &font_msSansSerif_14_0x5c},
#else
  // character: '\' == ''
  {0x5c, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: ']'
  {0x5d, &font_msSansSerif_14_0x5d},
#else
  // character: ']' == ''
  {0x5d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '^'
  {0x5e, &font_msSansSerif_14_0x5e},
#else
  // character: '^' == ''
  {0x5e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '_'
  {0x5f, &font_msSansSerif_14_0x5f},
#else
  // character: '_' == ''
  {0x5f, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '`'
  {0x60, &font_msSansSerif_14_0x60},
#else
  // character: '`' == ''
  {0x60, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'a'
  {0x61, &font_msSansSerif_14_0x61},
#else
  // character: 'a' == ''
  {0x61, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'b'
  {0x62, &font_msSansSerif_14_0x62},
#else
  // character: 'b' == ''
  {0x62, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'c'
  {0x63, &font_msSansSerif_14_0x63},
#else
  // character: 'c' == ''
  {0x63, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'd'
  {0x64, &font_msSansSerif_14_0x64},
#else
  // character: 'd' == ''
  {0x64, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'e'
  {0x65, &font_msSansSerif_14_0x65},
#else
  // character: 'e' == ''
  {0x65, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'f'
  {0x66, &font_msSansSerif_14_0x66},
#else
  // character: 'f' == ''
  {0x66, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'g'
  {0x67, &font_msSansSerif_14_0x67},
#else
  // character: 'g' == ''
  {0x67, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'h'
  {0x68, &font_msSansSerif_14_0x68},
#else
  // character: 'h' == ''
  {0x68, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'i'
  {0x69, &font_msSansSerif_14_0x69},
#else
  // character: 'i' == ''
  {0x69, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'j'
  {0x6a, &font_msSansSerif_14_0x6a},
#else
  // character: 'j' == ''
  {0x6a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'k'
  {0x6b, &font_msSansSerif_14_0x6b},
#else
  // character: 'k' == ''
  {0x6b, &font_msSansSerif_14_0x},
#endif

#if (0x049 == 0x0)
  // character: 'l'
  {0x6c, &font_msSansSerif_14_0x6c},
#else
  // character: 'l' == 'I'
  {0x6c, &font_msSansSerif_14_0x49},
#endif

#if (0x0 == 0x0)
  // character: 'm'
  {0x6d, &font_msSansSerif_14_0x6d},
#else
  // character: 'm' == ''
  {0x6d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'n'
  {0x6e, &font_msSansSerif_14_0x6e},
#else
  // character: 'n' == ''
  {0x6e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'o'
  {0x6f, &font_msSansSerif_14_0x6f},
#else
  // character: 'o' == ''
  {0x6f, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'p'
  {0x70, &font_msSansSerif_14_0x70},
#else
  // character: 'p' == ''
  {0x70, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'q'
  {0x71, &font_msSansSerif_14_0x71},
#else
  // character: 'q' == ''
  {0x71, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'r'
  {0x72, &font_msSansSerif_14_0x72},
#else
  // character: 'r' == ''
  {0x72, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 's'
  {0x73, &font_msSansSerif_14_0x73},
#else
  // character: 's' == ''
  {0x73, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 't'
  {0x74, &font_msSansSerif_14_0x74},
#else
  // character: 't' == ''
  {0x74, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'u'
  {0x75, &font_msSansSerif_14_0x75},
#else
  // character: 'u' == ''
  {0x75, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'v'
  {0x76, &font_msSansSerif_14_0x76},
#else
  // character: 'v' == ''
  {0x76, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'w'
  {0x77, &font_msSansSerif_14_0x77},
#else
  // character: 'w' == ''
  {0x77, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'x'
  {0x78, &font_msSansSerif_14_0x78},
#else
  // character: 'x' == ''
  {0x78, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'y'
  {0x79, &font_msSansSerif_14_0x79},
#else
  // character: 'y' == ''
  {0x79, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: 'z'
  {0x7a, &font_msSansSerif_14_0x7a},
#else
  // character: 'z' == ''
  {0x7a, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '{'
  {0x7b, &font_msSansSerif_14_0x7b},
#else
  // character: '{' == ''
  {0x7b, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '|'
  {0x7c, &font_msSansSerif_14_0x7c},
#else
  // character: '|' == ''
  {0x7c, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '}'
  {0x7d, &font_msSansSerif_14_0x7d},
#else
  // character: '}' == ''
  {0x7d, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '~'
  {0x7e, &font_msSansSerif_14_0x7e},
#else
  // character: '~' == ''
  {0x7e, &font_msSansSerif_14_0x},
#endif

#if (0x0 == 0x0)
  // character: '\x007f'
  {0x7f, &font_msSansSerif_14_0x7f}
#else
  // character: '\x007f' == ''
  {0x7f, &font_msSansSerif_14_0x}
#endif

};


const tFont font_msSansSerif_14 = { 96, font_msSansSerif_14_array };

